[project]
name = "spark_calibration"
version = "2.0.0"
authors = [
  { name="Jaya", email="jaya.kommuru@meesho.com"}
]
description = "Calibrating model scores/probabilities with PySpark DataFrames"
license = "Apache-2.0"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "plotly>=6.5.2",
    "pyspark>=4.1.1",
    "scikit-learn>=1.8.0",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/Meesho/spark_calibration"
"Bug Tracker" = "https://github.com/Meesho/spark_calibration/issues"
"Documentation" = "https://github.com/Meesho/spark_calibration#readme"